baseURL = "https://trudramukerji14.github.io/"
locale = "en-us"
title = "TMuk's Blog"
theme = "PaperMod"
[pagination]
  pagerSize = 5

[params]
  author = "TRM"
  description = "Thoughts on research, software, etc"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  [params.homeInfoParams]
    Title = "Hi, I'm Tantrik"
    Content = "Welcome to my corner of the internet. I write about software, math, and generally things I find interesting."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/trudramukerji14"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$'], ['\begin{equation}', '\end{equation}'], ['\begin{align}', '\end{align}']]
    inline = [['\(', '\)'], ['$', '$']]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
